### ISSUE TITLE
danny final project proposal

### ISSUE THREAD

**Issue by dannyalaska** [dannyalaska/final_project_wdi#1]
# Final Project Proposal
# OK FINE

I am going to make an app that will help users figure out what sort of cardio they should be doing and what days should be a specific type of cardio. 

A user is going to be able to go into the app and select how many days a week they can commit to doing cardio and then how long each day they have max to do cardio. 

The app is then going to give specific cardio workouts for each day: how long to spend and what intensity the user should be at during each segment of that cardio.  

Ideally I'd pair the workouts with specific heart rate training zones, but since we won't have that data it is going to have to rely solely on perceived exertion.  

The calculations are gonna be an issue and getting the workouts to look pretty is going to be a pain.  But it should showcase more than just my game making abilities.

**Comment by jasonseminara** [comment]
I don't think I get it. How much more are you writing beyond what Phaser provides? 

You already have two other shooting games on your portfolio. I'd like to see something different that shows off your skills as a web developer, not only a games designer.

**Comment by dannyalaska** [comment]
At the risk of sounding snarky. So do I.  Except that I am well-aware of my timeline and my own limitations as a web developer.  I had ambitions to create an app that helped build cardio training programs based on how many days per week and how much time per day one could dedicate to exercising except that I am extremely unsure about my abilities to have any sort of product by the middle of next week.

**Comment by jasonseminara** [comment]
approved
